language: node_js
node_js: node

dist: bionic

cache: yarn
install: yarn

before_script: skip

script:
  - yarn build
  - rm -rf `ls -A | sed "/^build$/d"`
  - mv build/* .
  - rm -rf build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: arnohovhannisyan/vscode-syncify
  target-branch: gh-pages
  on:
    branch: master
